services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sabine-images
    container_name: sabine-images
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env